version: "3"

services:
  requirements:
    volumes:
      - ./:/code
  assets:
    volumes:
      - ./:/code
  admin_assets:
    volumes:
      - ./:/code
  worker:
    volumes:
      - ./:/code
  admin:
    volumes:
      - ./:/code
  web:
    volumes:
      - ./:/code
  api:
    volumes:
      - ./:/code

# Additional configuration for development on services linked with osf.io

#  beat:
#    volumes:
#      - ./:/code

#  fakecas:
#    image: quay.io/centerforopenscience/fakecas:master
#    command: fakecas -host=0.0.0.0:8080 -osfhost=localhost:5000 -dbaddress=postgres://postgres@postgres:5432/osf?sslmode=disable

#  wb:
#    volumes:
#      - ../waterbutler:/code

#  wb_worker:
#    volumes:
#      - ../waterbutler:/code

#  wb_requirements:
#    volumes:
#      - ../waterbutler:/code

#  mfr:
#    volumes:
#      - ../modular-file-renderer:/code

#  mfr_requirements:
#    volumes:
#      - ../modular-file-renderer:/code

#  preprints:
#    volumes:
#      - ../ember-preprints:/code
#
##      # Use this for ember-osf linked development:
##      - preprints_dist_vol:/code/dist
##      - ../ember-osf:/ember-osf
##    depends_on:
##      - emberosf
##    command: /bin/bash -c "cd /ember-osf && yarn link && cd /code && yarn link @centerforopenscience/ember-osf && yarn --pure-lockfile --ignore-engines && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false && ./node_modules/ember-cli/bin/ember serve --host 0.0.0.0 --port 4200"

#  registries:
#    volumes:
#      - ../ember-osf-registries:/code
#
##      # Use this for ember-osf linked development:
##      - registries_dist_vol:/code/dist
##      - ../ember-osf:/ember-osf
##    depends_on:
##      - emberosf
##    command: /bin/bash -c "cd /ember-osf && yarn link && cd /code && yarn link @centerforopenscience/ember-osf && yarn --pure-lockfile --ignore-engines && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false && ./node_modules/ember-cli/bin/ember serve --host 0.0.0.0 --port 4300"

#  # Use this for ember-osf linked development:
#  emberosf:
#    build: ../ember-osf
#    command: /bin/bash -c "yarn --pure-lockfile --ignore-engines && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false"
#    volumes:
#      - ../ember-osf:/code
